// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDptqJgPDPPXKYiEg3zag_9RMoVktTG2A',
    appId: '1:736905207914:web:33054a9c6b753639a6ea13',
    messagingSenderId: '736905207914',
    projectId: 'vitrine-8d284',
    authDomain: 'vitrine-8d284.firebaseapp.com',
    storageBucket: 'vitrine-8d284.appspot.com',
    measurementId: 'G-ETZE4B3WRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCculN92aX6bszucI-x98rUTrrKtpuZ50k',
    appId: '1:736905207914:android:4e781f099c575d31a6ea13',
    messagingSenderId: '736905207914',
    projectId: 'vitrine-8d284',
    storageBucket: 'vitrine-8d284.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy2GcRe8VVcG1_gkXawL6nRhwfG93nMrg',
    appId: '1:736905207914:ios:ba03470cb57abd69a6ea13',
    messagingSenderId: '736905207914',
    projectId: 'vitrine-8d284',
    storageBucket: 'vitrine-8d284.appspot.com',
    iosBundleId: 'com.example.vitrine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy2GcRe8VVcG1_gkXawL6nRhwfG93nMrg',
    appId: '1:736905207914:ios:ba03470cb57abd69a6ea13',
    messagingSenderId: '736905207914',
    projectId: 'vitrine-8d284',
    storageBucket: 'vitrine-8d284.appspot.com',
    iosBundleId: 'com.example.vitrine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDptqJgPDPPXKYiEg3zag_9RMoVktTG2A',
    appId: '1:736905207914:web:582aa2534c95a9b2a6ea13',
    messagingSenderId: '736905207914',
    projectId: 'vitrine-8d284',
    authDomain: 'vitrine-8d284.firebaseapp.com',
    storageBucket: 'vitrine-8d284.appspot.com',
    measurementId: 'G-PPSH98RXNH',
  );
}
